### ISSUE TITLE
Remove count on pagination for facility tables

### ISSUE THREAD

**Issue by patricknowlan** [540co/epa-rfi#109]

**Comment by ostranme** [comment]
This is default behavior and built into the directive we are using. 
https://github.com/daniel-nagy/md-data-table
- Can remove total count but the directive will still show 1 of .....
- Recommend using a different data table as a future feature enhancement.

**Comment by patricknowlan** [comment]
This is no longer an issue. Back end was updated and now displays correct numbers for pagination. Closing issue.
