### ISSUE TITLE
Angular Material "switch" element does not display in IE 9

### ISSUE THREAD

**Issue by patricknowlan** [540co/epa-rfi#21]
Browswer Version: 9.0.8112.16421
OS: Windows 7

IE9 screenshot:

<img width="1257" alt="screen shot 2015-12-16 at 12 18 23 pm" src="https://cloud.githubusercontent.com/assets/6303436/11848220/454e41ba-a3ef-11e5-998c-1370e2c72ffd.png">

Should display like this:

<img width="1280" alt="screen shot 2015-12-16 at 12 20 10 pm" src="https://cloud.githubusercontent.com/assets/6303436/11848251/6e7f8012-a3ef-11e5-815a-92687397b4f5.png">

**Comment by ostranme** [comment]
Removed angular switch from features. No longer using this angular material element.
