### ISSUE TITLE
Zipcode input placeholder returns no results

### ISSUE THREAD

**Issue by patricknowlan** [540co/epa-rfi#61]
The zipcode 22205 is a bad example because it returns no results. It should be updated to a zipcode that returns actual results like 22031.

<img width="324" alt="screen shot 2015-12-22 at 12 02 05 pm" src="https://cloud.githubusercontent.com/assets/6303436/11961015/e2b011aa-a8a3-11e5-8099-a8ee6815dad2.png">

**Comment by lundstjb** [comment]
Closed with d404f1f5f56fb944c1c6b3520833a5ef41fa590c
